# Generated by Django 2.0.4 on 2018-08-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='video',
        ),
    ]
