# Generated by Django 2.0.4 on 2018-08-27 18:54

from django.db import migrations, models
import meal.models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_remove_meal_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=meal.models.upload_video),
        ),
    ]
