# Generated by Django 2.0.4 on 2018-08-26 10:53

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiefProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], max_length=50, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only alphanumeric characters are allowed.')])),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to=user_profile.models.upload_img)),
                ('cv', models.FileField(upload_to=user_profile.models.upload_img)),
                ('state', models.NullBooleanField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], max_length=50, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only alphanumeric characters are allowed.')])),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=user_profile.models.upload_img)),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 8, 26, 10, 53, 27, 794348, tzinfo=utc))),
            ],
        ),
    ]
