# Generated by Django 2.0.4 on 2018-08-26 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20180826_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 26, 12, 26, 51, 153354, tzinfo=utc)),
        ),
    ]
