# Generated by Django 2.0.4 on 2018-08-27 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20180827_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 27, 18, 54, 33, 614847, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 27, 18, 54, 33, 616847, tzinfo=utc)),
        ),
    ]
