# Generated by Django 2.0.4 on 2018-09-01 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20180827_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 1, 14, 7, 40, 116196, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 1, 14, 7, 40, 116196, tzinfo=utc)),
        ),
    ]
